[build]
target = "i686-unknown-none.json" # Build for a no-os target,
rustflags = ["-C", "link-args=-Ttext 0x7C00"]

[unstable]
build-std = ["core", "compiler_builtins"] # Build core and it's dependency compiler_builtins from src
build-std-features = ["compiler-builtins-mem"] # Build memset, etc. from compiler_builtins crate