[build]
target = "x86_64-unknown-none.json" # Build for a no-os target,

[target.'cfg(target_os="none")']
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins"] # Build core and it's dependency compiler_builtins from src
build-std-features = ["compiler-builtins-mem"] # Build memset, etc. from compiler_builtins crate